[workspace]

members = [
    "concrete-optimizer",
    "v0-parameters",
    "concrete-optimizer-cpp",
    "charts",
    "brute-force-optimizer",
]


[profile.test]


overflow-checks = true

[profile.release]
overflow-checks = true
