#!/bin/env bash

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NAME=v0-parameters
EXE=${ROOT_DIR}/target/release/${NAME}

if ! [ -e "$EXE" ]; then
    echo "Let's build the optimizer before running it ..."
fi

cd $ROOT_DIR
cargo run --release --quiet --bin v0-parameters -- $@
