[package]
name = "concrete-core-bench"
version = "0.0.0"
edition = "2018"
license = "BSD-3-Clause-Clear"

[dependencies]
concrete-core = { path="../concrete-core" }
concrete-core-fixture = { path="../concrete-core-fixture" }
paste = "1.0"
criterion = "0.3.5"

[features]
backend_core = ["concrete-core/backend_core", "concrete-core-fixture/backend_core"]
