version: 2
registries:
  ghcr-io: # Define access for a private registry
    type: docker-registry
    url: ghcr.io
    username: ${{secrets.BOT_USERNAME}}
    password: ${{secrets.BOT_TOKEN}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every sunday
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: "docker"
    directory: "/docker"
    registries:
      - ghcr-io # Allow version updates for dependencies in this registry
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "chore(ci)"
