root: ./docs

redirects:
  getting-started/fhe_basics: core-features/fhe_basics.md
  getting-started/installing: get-started/installing.md
  getting-started/quick_start: get-started/quick_start.md
  getting-started/compatibility: get-started/compatibility.md
  getting-started/terminology_and_structure: get-started/terminology.md
  tutorial/decorator: compilation/decorator.md
  tutorial/progressbar: execution-analysis/progressbar.md
  tutorial/formatting: execution-analysis/formatting_and_drawing.md
  tutorial/tagging: core-features/tagging.md
  tutorial/extensions: core-features/extensions.md
  tutorial/comparisons: core-features/comparisons.md
  tutorial/minmax: core-features/minmax.md
  tutorial/bitwise: core-features/bitwise.md
  tutorial/table_lookups: core-features/table_lookups.md
  tutorial/bit_extraction: core-features/bit_extraction.md
  tutorial/truncating: core-features/truncating.md
  tutorial/rounding: core-features/rounding.md
  tutorial/floating_points: core-features/floating_points.md
  tutorial/multi_precision: compilation/multi_precision.md
  tutorial/multi_parameters: compilation/multi_parameters.md
  tutorial/simulation: execution-analysis/simulation.md
  tutorial/direct_circuits: compilation/direct_circuits.md
  tutorial/statistics: compilation/statistics.md
  tutorial/workarounds: core-features/workarounds.md
  tutorial/composition: compilation/composition.md
  application-tutorial/key_value_database: tutorials/see-all-tutorials.md
  application-tutorial/sha256: tutorials/see-all-tutorials.md
  application-tutorial/game_of_life: tutorials/see-all-tutorials.md
  howto/configure: guides/configure.md
  howto/manage_keys: guides/manage_keys.md
  howto/deploy: guides/deploy.md
  howto/reuse_arguments: compilation/reuse_arguments.md
  howto/debug: execution-analysis/debug.md
  howto/call_from_other_language: explanations/call_from_other_language.md
  dev/fusing: explanations/fusing.md
  dev/backends: explanations/backends/README.md
  dev/backends/new_backend: explanations/backends/new_backend.md
  dev/compilation: dev/compilation/compiler_workflow.md
  dev/compilation/optimizer: explanations/optimizer.md
  dev/compilation/dialects: explanations/dialects.md
  dev/compilation/FHELinalgDialect: explanations/FHELinalgDialect.md
  dev/compilation/FHEDialect: explanations/FHEDialect.md
  dev/compilation/TFHEDialect: explanations/TFHEDialect.md
  dev/compilation/ConcreteDialect: explanations/ConcreteDialect.md
  dev/compilation/TracingDialect: explanations/TracingDialect.md
  dev/compilation/RTDialect: explanations/RTDialect.md
  dev/compilation/SDFGDialect: explanations/SDFGDialect.md
  dev/security/security_curves: explanations/security.md
  explanations/security_curves: explanations/security.md
  dev/setup/layout: explanations/layout.md
