[package]
# see https://doc.rust-lang.org/cargo/reference/manifest.html
name = "concrete-optimizer-cpp"
version = "0.1.0"
authors = [""]
edition = "2021"

[dependencies]
cxx = "1"
concrete-optimizer = { path = "../concrete-optimizer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
cxx-build = "1"

[lib]
path = "src/concrete-optimizer.rs"
crate-type = ["lib", "staticlib"]
