FROM python:3.10-slim

ARG version

# provide the `ld` binary required by the compiler
RUN apt update && apt install -y binutils graphviz

RUN pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu --extra-index-url https://pypi.zama.ai concrete-python==${version}
