FROM ghcr.io/zama-ai/hdk-env

RUN echo "source /hdk/.docker_venv/bin/activate" >> /root/.bashrc && \
    echo "if [[ \"\$?\" != \"0\" ]]; then" >> /root/.bashrc && \
    echo "    python3 -m venv /hdk/.docker_venv" >> /root/.bashrc && \
    echo "    source /hdk/.docker_venv/bin/activate" >> /root/.bashrc && \
    echo "    cd /hdk/ && make setup_env" >> /root/.bashrc && \
    echo "fi" >> /root/.bashrc && \
    echo "export LD_PRELOAD=/compiler/build/lib/Runtime/libZamalangRuntime.so" >> /root/.bashrc

WORKDIR /hdk

ENTRYPOINT ["/bin/bash", "-l"]
