ARG BASEIMAGE=ghcr.io/zama-ai/concrete/compiler-ci:latest
# hadolint ignore=DL3006
FROM $BASEIMAGE

# Setup CUDA
COPY --from=ghcr.io/zama-ai/concrete/cuda:11-8 /usr/local/cuda-11.8/ /usr/local/cuda-11.8/
ENV PATH="$PATH:/usr/local/cuda-11.8/bin"
