mod analyze;
mod complexity;
mod fast_keyswitch;
mod feasible;
pub mod keys_spec;
mod operations_value;
pub mod optimize;
mod partitionning;
mod partitions;
mod precision_cut;
mod symbolic_variance;
mod union_find;
mod variance_constraint;
