FROM quay.io/pypa/manylinux_2_28_x86_64

RUN dnf update -y
RUN dnf install -y ninja-build hwloc-devel
# Install boost
ADD https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.gz /boost_1_71_0.tar.gz
RUN tar -xzvf /boost_1_71_0.tar.gz
WORKDIR /boost_1_71_0
RUN ./bootstrap.sh && ./b2 --with-filesystem install
# Set the python path. Options: [cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]
ARG python_tag=cp38-cp38
# Install python deps
RUN /opt/python/${python_tag}/bin/pip install numpy pybind11==2.8 PyYAML
# Setup HPX
COPY --from=ghcr.io/zama-ai/hpx:libc_2_28 /hpx /hpx
ENV HPX_INSTALL_DIR=/hpx/build
# Setup LLVM
COPY /llvm-project /llvm-project
# Setup and build compiler
COPY /compiler /compiler
WORKDIR /compiler
RUN make DATAFLOW_EXECUTION_ENABLED=ON Python3_EXECUTABLE=/opt/python/${python_tag}/bin/python python-bindings
# Build wheel
RUN /opt/python/${python_tag}/bin/pip wheel --no-deps -w /wheels .
RUN auditwheel repair /wheels/*.whl --plat manylinux_2_28_x86_64 -w /wheels
