FROM quay.io/pypa/manylinux_2_24_x86_64

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential ninja-build 
# Setup LLVM
COPY /llvm-project /llvm-project
# Setup Concrete
COPY --from=ghcr.io/zama-ai/concrete-api-env:latest /target/release /concrete/target/release
ENV CONCRETE_PROJECT=/concrete
# Setup and build compiler
COPY .github/workflows/assets/Installation.md /
COPY /compiler /compiler
WORKDIR /compiler
RUN make BINDINGS_PYTHON_ENABLED=OFF concretecompiler
# Build tarball
RUN mkdir -p /tarballs/concretecompiler/lib /tarballs/concretecompiler/bin && \
    cp /compiler/build/bin/concretecompiler /tarballs/concretecompiler/bin && \
    cp /compiler/build/lib/libConcretelangRuntime.so /tarballs/concretecompiler/lib && \
    cp /Installation.md /tarballs/concretecompiler/
RUN cd /tarballs && tar -czvf concretecompiler.tar.gz concretecompiler