FROM quay.io/pypa/manylinux_2_24_x86_64

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential ninja-build 
# Set the python path. Options: [cp38-cp38, cp39-cp39, cp310-cp310]
ARG python_tag=cp38-cp38
# Install python deps
RUN /opt/python/${python_tag}/bin/pip install numpy pybind11==2.6.2 PyYAML
# Setup gcc7
COPY --from=ghcr.io/zama-ai/gcc7:latest /gcc7 /gcc7
ENV PATH=/gcc7/bin:$PATH
ENV LD_LIBRARY_PATH=/gcc7/lib/:/gcc7/lib64/:$LD_LIBRARY_PATH
ENV CC=/gcc7/bin/gcc-7.5.0
ENV CXX=/gcc7/bin/g++-7.5.0
# Setup LLVM
COPY /llvm-project /llvm-project
# Setup Concrete
COPY --from=ghcr.io/zama-ai/concrete-compiler-api-env:latest /target/release /concrete/target/release
ENV CONCRETE_PROJECT=/concrete
# Setup and build compiler
COPY /compiler /compiler
WORKDIR /compiler
RUN make -e CXX_COMPILER=$CXX CC_COMPILER=$CC Python3_EXECUTABLE=/opt/python/${python_tag}/bin/python python-bindings
# Fix MLIR package
RUN touch build/tools/concretelang/python_packages/concretelang_core/mlir/__init__.py
RUN touch build/tools/concretelang/python_packages/concretelang_core/mlir/dialects/__init__.py
# Build wheel
RUN /opt/python/${python_tag}/bin/pip wheel --no-deps -w /wheels .
RUN auditwheel repair /wheels/*.whl --plat manylinux_2_24_x86_64 -w /wheels