from qbozama/mlir:69c6ea9038e5f3ef91a3c5ab59fae3276f95628b

ENV PYTHONPATH=/llvm-project/build/python:/compiler/build/python:$PYTHONPATH

COPY /compiler /compiler
WORKDIR /compiler
RUN mkdir -p build && make -B build && make -C build all zamacompiler