#ifndef BOOTSTRAP_OPTIMIZED_H
#define BOOTSTRAP_OPTIMIZED_H

#define OPT_DECOMPOSITION_LEVEL_COUNT 1
#define OPT_DECOMPOSITION_BASE_LOG 22
#define OPT_GLWE_DIMENSION 1
#define OPT_OUT_SIZE 8193
#define OPT_INPUT_SIZE 895
#define OPT_TLU_SIZE 8192
#define OPT_INPUT_LWE_DIMENSION 894
#define OPT_POLYNOMIAL_SIZE 8192
#define OPT_POLYNOMIAL_SIZE_LOG 13

#define OPT_FOURIER_POLYNOMIAL_SIZE (OPT_POLYNOMIAL_SIZE / 2)
#define OPT_FOURIER_POLYNOMIAL_SIZE_LOG (OPT_POLYNOMIAL_SIZE_LOG-1)
#define OPT_GLWE_SIZE (OPT_GLWE_DIMENSION + 1)
#define OPT_ACCUMULATOR_SIZE (OPT_POLYNOMIAL_SIZE * OPT_GLWE_SIZE)
#endif
