name: Setup rust toolchain for concrete-cpu

description: Setup rust toolchain for concrete-cpu

runs:
  using: "composite"
  steps:
    - name: Install rust
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        toolchain: nightly-2024-09-30
        override: true
