name: Concrete Python Checks

on:
  workflow_call:

jobs:
  Checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install Platform Dependencies
        run: |
          sudo apt install -y graphviz libgraphviz-dev
      - name: Pre-Commit Checks
        run: |
          ./frontends/concrete-python/scripts/checks/checks.sh
