# Compile doc
name: Compile doc
on:
  push:

jobs:
  doc:
    name: Compile doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Compile doc
        run: cargo xtask check_doc