# Check formatting using rustfmt
# and lint with clippy
name: Rustfmt and Clippy check
on:
  push:
jobs:
  formatting:
    name: rustfmt
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Run rustfmt
        run: cargo xtask check_fmt

  clippy-check:
    name: clippy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - name: Run clippy
        run: cargo xtask check_clippy